name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Pashmak
      uses: pashmaklang/setup-pashmak@master
      with:
        pashmak-version: 0.8.1
    - name: Running Tests
      run: |
        pashmak test.pashm

    name: Test
